import type { Metadata } from 'next'
import Link from 'next/link'
import { Shield, ArrowLeft } from 'lucide-react'
import { SiteFooter } from '@/components/site-footer'

export const metadata: Metadata = {
  title: 'Terms of Service | Aiscern AI Detector',
  description: 'Aiscern terms of service. Use our AI detection tools freely. No spam, no misuse of detection results for harmful purposes.',
}

const LAST_UPDATED = 'March 10, 2025'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <header className="border-b border-border bg-surface/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-primary to-secondary flex items-center justify-center">
              <Shield className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="font-black gradient-text">Aiscern</span>
          </Link>
          <Link href="/" className="flex items-center gap-1.5 text-sm text-text-muted hover:text-text-primary transition-colors">
            <ArrowLeft className="w-4 h-4" /> Back to Home
          </Link>
        </div>
      </header>

      <main className="flex-1 max-w-4xl mx-auto w-full px-4 py-12">
        <div className="mb-10">
          <h1 className="text-4xl font-black text-text-primary mb-3">Terms of Service</h1>
          <p className="text-text-muted">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="space-y-8">
          <Section title="1. Acceptance of Terms">
            <p>
              By accessing or using Aiscern (&quot;Service&quot;), operated by Anas Ali, you agree to be bound by these Terms of Service.
              If you do not agree, you must not use the Service. We reserve the right to update these terms at any time.
            </p>
          </Section>

          <Section title="2. Description of Service">
            <p>
              Aiscern is an AI-powered content detection platform that analyzes text, images, audio, and video to determine
              whether content may have been generated by artificial intelligence. Detection results are probabilistic and
              should not be treated as definitive proof.
            </p>
          </Section>

          <Section title="3. User Accounts">
            <ul>
              <li>You must be at least 13 years old to create an account</li>
              <li>You are responsible for maintaining the security of your account credentials</li>
              <li>You must provide accurate information when registering</li>
              <li>One account per person — creating multiple accounts to circumvent limits is prohibited</li>
              <li>You are responsible for all activity that occurs under your account</li>
            </ul>
          </Section>

          <Section title="4. Acceptable Use">
            <p>You agree not to use Aiscern to:</p>
            <ul>
              <li>Upload illegal content, including CSAM, malware, or copyright-infringing material</li>
              <li>Attempt to bypass or circumvent AI detection systems for malicious purposes</li>
              <li>Submit content for the purpose of harassing, defaming, or targeting individuals</li>
              <li>Reverse engineer, scrape, or extract our AI models or data</li>
              <li>Use the service for automated bulk analysis without prior written permission</li>
              <li>Misrepresent detection results as legally binding proof in court or legal proceedings</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
            </ul>
          </Section>

          <Section title="5. Content You Submit">
            <p>
              You retain ownership of all content you submit to Aiscern. By submitting content, you grant us a limited,
              non-exclusive license to process that content solely for the purpose of providing detection results.
            </p>
            <p>
              You represent that you have the right to submit all content you upload and that it does not violate any
              applicable laws or third-party rights.
            </p>
          </Section>

          <Section title="6. Detection Results Disclaimer">
            <p className="font-semibold text-amber-400">IMPORTANT:</p>
            <ul>
              <li>AI detection results are probabilistic estimates, not definitive facts</li>
              <li>Aiscern results should not be used as the sole basis for legal, academic, or professional decisions</li>
              <li>We do not guarantee 100% accuracy — false positives and false negatives can occur</li>
              <li>You are solely responsible for how you interpret and use detection results</li>
            </ul>
          </Section>

          <Section title="7. Intellectual Property">
            <p>
              The Aiscern platform, including its design, AI models, codebase (MIT License), and branding, is the property
              of Anas Ali. You may not use our trademarks,
              logos, or branding without prior written permission.
            </p>
          </Section>

          <Section title="8. Service Availability">
            <p>
              We strive for high availability but do not guarantee uninterrupted service. We may suspend or terminate the
              service at any time for maintenance, updates, or other reasons. We are not liable for any losses resulting
              from service downtime.
            </p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, AISCERN AND ANAS ALI SHALL NOT BE LIABLE FOR ANY INDIRECT,
              INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT
              LIMITED TO LOSS OF DATA, REVENUE, OR REPUTATION.
            </p>
          </Section>

          <Section title="10. Termination">
            <p>
              We reserve the right to suspend or terminate accounts that violate these Terms. You may delete your account
              at any time from the Settings page. Upon termination, your data will be deleted in accordance with our
              Privacy Policy.
            </p>
          </Section>

          <Section title="11. Governing Law">
            <p>
              These Terms are governed by applicable international law. Any disputes shall be resolved through good-faith
              negotiation, and failing that, through binding arbitration.
            </p>
          </Section>

          <Section title="12. Contact">
            <p>
              For questions about these Terms, contact:<br />
              <strong>Anas Ali</strong><br />
              Email: <a href="mailto:legal@aiscern.com" className="text-primary hover:underline">legal@aiscern.com</a>
            </p>
          </Section>
        </div>
      </main>

      <SiteFooter />
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-bold text-text-primary mb-4 pb-2 border-b border-border">{title}</h2>
      <div className="space-y-3 text-text-secondary text-sm leading-relaxed">{children}</div>
    </section>
  )
}
