name                = "detectai-pipeline-c"
main                = "workers/worker-c.ts"
compatibility_date  = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev         = false

[[d1_databases]]
binding       = "DB"
database_name = "detectai-pipeline"
database_id   = "50f5e26a-c794-4cfa-b2b7-2bbd1d7c045c"

[triggers]
crons = ["*/1 * * * *"]

[vars]
HF_REPO = "saghi776/detectai-dataset"
